In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('C:\\Users\\pk540\\OneDrive\\Desktop\\test\\Dataset\\healthcare-dataset-stroke-data.csv')
df.head()

id  gender   age  hypertension  heart_disease ever_married  \
0   9046    Male  67.0             0              1          Yes   
1  51676  Female  61.0             0              0          Yes   
2  31112    Male  80.0             0              1          Yes   
3  60182  Female  49.0             0              0          Yes   
4   1665  Female  79.0             1              0          Yes   

       work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0        Private          Urban             228.69  36.6  formerly smoked   
1  Self-employed          Rural             202.21   NaN     never smoked   
2        Private          Rural             105.92  32.5     never smoked   
3        Private          Urban             171.23  34.4           smokes   
4  Self-employed          Rural             174.12  24.0     never smoked   

   stroke  
0       1  
1       1  
2       1  
3       1  
4       1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 5110 non-null   int64  
 1   gender             5110 non-null   object 
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64  
 4   heart_disease      5110 non-null   int64  
 5   ever_married       5110 non-null   object 
 6   work_type          5110 non-null   object 
 7   Residence_type     5110 non-null   object 
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object 
 11  stroke             5110 non-null   int64  
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB


In [4]:
df.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [5]:
df['bmi'] = df['bmi'].fillna(df['bmi'].mean())

In [6]:
df.drop_duplicates(inplace=True)

In [7]:
df.drop('id',axis=1,inplace=True)

In [8]:
df.head()

gender   age  hypertension  heart_disease ever_married      work_type  \
0    Male  67.0             0              1          Yes        Private   
1  Female  61.0             0              0          Yes  Self-employed   
2    Male  80.0             0              1          Yes        Private   
3  Female  49.0             0              0          Yes        Private   
4  Female  79.0             1              0          Yes  Self-employed   

  Residence_type  avg_glucose_level        bmi   smoking_status  stroke  
0          Urban             228.69  36.600000  formerly smoked       1  
1          Rural             202.21  28.893237     never smoked       1  
2          Rural             105.92  32.500000     never smoked       1  
3          Urban             171.23  34.400000           smokes       1  
4          Rural             174.12  24.000000     never smoked       1

In [9]:
features = df.iloc[:,:-1]
target = df.iloc[:,-1]

In [10]:
cols = features[['gender', 'ever_married', 'work_type', 'Residence_type','smoking_status']]

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
features['gender'] = le.fit_transform(features['gender'])
features['ever_married'] = le.fit_transform(features['ever_married'])
features['work_type'] = le.fit_transform(features['work_type'])
features['Residence_type'] = le.fit_transform(features['Residence_type'])
features['smoking_status'] = le.fit_transform(features['smoking_status'])

In [12]:
df.head()

gender   age  hypertension  heart_disease ever_married      work_type  \
0    Male  67.0             0              1          Yes        Private   
1  Female  61.0             0              0          Yes  Self-employed   
2    Male  80.0             0              1          Yes        Private   
3  Female  49.0             0              0          Yes        Private   
4  Female  79.0             1              0          Yes  Self-employed   

  Residence_type  avg_glucose_level        bmi   smoking_status  stroke  
0          Urban             228.69  36.600000  formerly smoked       1  
1          Rural             202.21  28.893237     never smoked       1  
2          Rural             105.92  32.500000     never smoked       1  
3          Urban             171.23  34.400000           smokes       1  
4          Rural             174.12  24.000000     never smoked       1

In [13]:
features.head()

gender   age  hypertension  heart_disease  ever_married  work_type  \
0       1  67.0             0              1             1          2   
1       0  61.0             0              0             1          3   
2       1  80.0             0              1             1          2   
3       0  49.0             0              0             1          2   
4       0  79.0             1              0             1          3   

   Residence_type  avg_glucose_level        bmi  smoking_status  
0               1             228.69  36.600000               1  
1               0             202.21  28.893237               2  
2               0             105.92  32.500000               2  
3               1             171.23  34.400000               3  
4               0             174.12  24.000000               2

In [14]:
features.work_type.value_counts()

2    2925
3     819
4     687
0     657
1      22
Name: work_type, dtype: int64

In [15]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(features,target,random_state=2,test_size=0.3,stratify=target)

In [16]:
from sklearn.ensemble import AdaBoostClassifier
adaboost = AdaBoostClassifier()
adaboost.fit(xtrain,ytrain)
ypred_adaboost = adaboost.predict(xtest)

In [17]:
train = adaboost.score(xtrain,ytrain)
test = adaboost.score(xtest,ytest)

print(f'Training_Acc : {train}\nTesting_Acc : {test}')

Training_Acc : 0.9513558848196813
Testing_Acc : 0.9510763209393346


In [18]:
from sklearn.metrics import confusion_matrix,classification_report
cm = confusion_matrix(ytest,ypred_adaboost)
cr = classification_report(ytest,ypred_adaboost)

print(f'{cm}\n{cr}')

[[1456    2]
 [  73    2]]
              precision    recall  f1-score   support

           0       0.95      1.00      0.97      1458
           1       0.50      0.03      0.05        75

    accuracy                           0.95      1533
   macro avg       0.73      0.51      0.51      1533
weighted avg       0.93      0.95      0.93      1533



In [19]:
pip install imblearn

Note: you may need to restart the kernel to use updated packages.


In [20]:
from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler()
x_sample,y_sample = rus.fit_resample(features,target)

In [21]:
xtrain,xtest,ytrain,ytest = train_test_split(x_sample,y_sample,random_state=2,test_size=0.3)

In [22]:
adaboost.fit(xtrain,ytrain)
ypred_adaboost = adaboost.predict(xtest)

In [23]:
train = adaboost.score(x_sample,y_sample)
test = adaboost.score(xtest,ytest)

print(f'Training_Acc : {train}\nTesting_Acc : {test}')

Training_Acc : 0.7550200803212851
Testing_Acc : 0.66


In [24]:
cm = confusion_matrix(ytest,ypred_adaboost)
cr = classification_report(ytest,ypred_adaboost)

print(f'{cm}\n{cr}')

[[47 23]
 [28 52]]
              precision    recall  f1-score   support

           0       0.63      0.67      0.65        70
           1       0.69      0.65      0.67        80

    accuracy                           0.66       150
   macro avg       0.66      0.66      0.66       150
weighted avg       0.66      0.66      0.66       150



In [27]:
from sklearn.model_selection import GridSearchCV
parameter = {
    'n_estimators': [50, 100, 150],
    'learning_rate': [0.01, 0.1, 0.5, 1]
}

grid = GridSearchCV(adaboost, parameter, verbose=2)
grid.fit(x_sample, y_sample)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV] END ................learning_rate=0.01, n_estimators=50; total time=   0.0s
[CV] END ................learning_rate=0.01, n_estimators=50; total time=   0.0s
[CV] END ................learning_rate=0.01, n_estimators=50; total time=   0.0s
[CV] END ................learning_rate=0.01, n_estimators=50; total time=   0.0s
[CV] END ................learning_rate=0.01, n_estimators=50; total time=   0.0s
[CV] END ...............learning_rate=0.01, n_estimators=100; total time=   0.0s
[CV] END ...............learning_rate=0.01, n_estimators=100; total time=   0.0s
[CV] END ...............learning_rate=0.01, n_estimators=100; total time=   0.0s
[CV] END ...............learning_rate=0.01, n_estimators=100; total time=   0.0s
[CV] END ...............learning_rate=0.01, n_estimators=100; total time=   0.0s
[CV] END ...............learning_rate=0.01, n_estimators=150; total time=   0.0s
[CV] END ...............learning_rate=0.01, n_es

GridSearchCV(estimator=AdaBoostClassifier(),
             param_grid={'learning_rate': [0.01, 0.1, 0.5, 1],
                         'n_estimators': [50, 100, 150]},
             verbose=2)

In [28]:
grid.best_estimator_

AdaBoostClassifier(learning_rate=0.1)

In [29]:
adaboost = grid.best_estimator_
adaboost.fit(xtrain,ytrain)
ypred_adaboost = adaboost.predict(xtest)

In [31]:
train = adaboost.score(x_sample,y_sample)
test = adaboost.score(xtest,ytest)

print(f'Training_Acc : {train}\nTesting_Acc : {test}')

Training_Acc : 0.7429718875502008
Testing_Acc : 0.72


In [32]:
cm = confusion_matrix(ytest,ypred_adaboost)
cr = classification_report(ytest,ypred_adaboost)

print(f'{cm}\n{cr}')

[[43 27]
 [15 65]]
              precision    recall  f1-score   support

           0       0.74      0.61      0.67        70
           1       0.71      0.81      0.76        80

    accuracy                           0.72       150
   macro avg       0.72      0.71      0.71       150
weighted avg       0.72      0.72      0.72       150



In [34]:
import pickle
pickle.dump(adaboost,open('./model2.sav', 'wb'))

In [35]:
pickle.load(open('model2.sav', 'rb'))

AdaBoostClassifier(learning_rate=0.1)